### ISSUE TITLE
Kubernetes-Security-Slam-2023

### ISSUE THREAD

**Issue by sarkar-deb** [kubernetes/kompose#1788]
### What would you like to be added?

Open tasks for the Kubernetes Security Slam 2023

 - [x]  Task 1: Releases are being made via CI (https://github.com/kubernetes/kompose/issues/1785)
 - [x]  Task 2: Check that Images are Staged and Promoted Using Community Infra (**We don't use images**)
 - [x]  Task 3: Ensure SBOMs are Generated by Kubernetes BOM (https://github.com/kubernetes/kompose/issues/1786)
 - [x]  Task 4: Ensure SLSA Attestations are Generated when Possible (https://github.com/kubernetes/kompose/issues/1786)
 - [x]  Task 5: Ensure the Project has a VEX Feed (https://github.com/kubernetes/kompose/pull/1787)
 - [x]  Task 7: Set up CLOMonitor Tracking (https://github.com/cncf/clomonitor/pull/1382)
 - [x] Task 8: Check for Binary Artifacts (**Binary are not placed in repositories**)
 - [x] Task 9: Review the Code Review (**Already in place**)
 - [x] Task 10: Dangerous Workflow (**There are github actions to take care of workflows**)
 - [x] Task 11: Security Insights (**Current process have security checks, done via github actions**)
 - [x] Task 13: Dependency update tool (**Current repo uses dependabot**)

All above task were worked on and collaborated among @sarkar-deb @dipesh-rawat @rudrakshkarpe

### Why is this needed?

A checklist for task we have done.

**Comment by eddie-knight** [comment]
This checklist was developed by myself and @puerco to help guide contributions. When the project tracking kicks in on https://clomonitor.io then more of the security hygiene state will be visible as well.
