### ISSUE TITLE
[EPIC] Improvements to volumes

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#884]
Volumes is probably the number one problem when converting from Docker Compose to Kubernetes and thus we should add a solution for the conversion.

Suggestions: https://kubernetes.io/docs/concepts/api-extension/custom-resources/

Close / resolve these issues:

- [x] Error transforming objects https://github.com/kubernetes/kompose/issues/876
- [x] Add test cases / documentation for volume label https://github.com/kubernetes/kompose/issues/872
- [x] Fix volume long syntax https://github.com/kubernetes/kompose/issues/865
- [ ] Local volume from host conversion https://github.com/kubernetes/kompose/issues/855
- [ ] Supporting top-level volumes https://github.com/kubernetes/kompose/issues/447
- [x] Supporting host path volumes https://github.com/kubernetes/kompose/issues/109
- [ ] Supporting per-volume option https://github.com/kubernetes/kompose/issues/850

As well as:

- [ ] Improve errors and offer solutions rather than erroring
- [ ] Explain WHY it doesn't **clearly** within documentation as well as CLI
